# Generated by Django 6.0 on 2026-07-01 23:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_producto_gramos_sugeridos_producto_subtipo_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Al detal'), ('MAYORISTA', 'Al por mayor')], max_length=10)),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Fiado / Crédito')], max_length=10)),
                ('fecha', models.DateField()),
                ('total', models.PositiveIntegerField(default=0, editable=False)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.PositiveIntegerField()),
                ('costo_unitario', models.PositiveIntegerField(editable=False)),
                ('subtotal', models.PositiveIntegerField(editable=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_producto', to='ventas.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_esencia', models.PositiveIntegerField()),
                ('gramos_combo_extra', models.PositiveIntegerField(default=0)),
                ('valor_combo_extra', models.PositiveIntegerField(default=0)),
                ('valor_preparacion', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.PositiveIntegerField(editable=False)),
                ('precio_venta', models.PositiveIntegerField(editable=False)),
                ('subtotal', models.PositiveIntegerField(editable=False)),
                ('envase', models.ForeignKey(limit_choices_to={'subtipo_insumo': 'ENVASE'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_envase', to='productos.producto')),
                ('esencia', models.ForeignKey(limit_choices_to={'subtipo_insumo': 'ESENCIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_esencia', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_perfume', to='ventas.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
