# Generated by Django 6.0 on 2026-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagada_en_caja',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
