# Generated by Django 6.0 on 2026-07-01 23:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0002_venta_pagada_en_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.PositiveIntegerField(editable=False)),
                ('saldo_pendiente', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', editable=False, max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiado', to='ventas.venta')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AbonoFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_fiado', to=settings.AUTH_USER_MODEL)),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='finanzas.fiado')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('OTORGADO', 'Otorgado (Esencial le presta a alguien)'), ('RECIBIDO', 'Recibido (alguien le presta a Esencial)')], max_length=10)),
                ('monto_capital', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de interés total acordado (ej. 10 = 10%). Déjalo en 0 si no aplica.', max_digits=5)),
                ('monto_total_a_pagar', models.PositiveIntegerField(editable=False)),
                ('saldo_pendiente', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAGADO', 'Pagado')], default='ACTIVO', editable=False, max_length=10)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AbonoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_prestamo', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='finanzas.prestamo')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
