# Generated by Django 6.0.6 on 2026-07-01 20:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo_producto', models.CharField(choices=[('INSUMO', 'Insumo'), ('PREPARADO', 'Preparado (con receta)'), ('TERMINADO', 'Terminado (reventa)')], max_length=10)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('ML', 'Mililitro'), ('G', 'Gramo')], max_length=5)),
                ('costo_compra', models.PositiveIntegerField(default=0)),
                ('precio_detal', models.PositiveIntegerField(default=0)),
                ('margen_detal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('precio_mayorista', models.PositiveIntegerField(blank=True, null=True)),
                ('margen_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('disponible_mayorista', models.BooleanField(default=False)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
