# Generated by Django 6.0 on 2026-07-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='gramos_sugeridos',
            field=models.PositiveIntegerField(blank=True, help_text='Solo para envases: gramos de esencia sugeridos para ese tamaño (ej. 30ml → 13g). Editable al vender.', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='subtipo_insumo',
            field=models.CharField(blank=True, choices=[('ESENCIA', 'Esencia'), ('ENVASE', 'Envase'), ('EXTRA', 'Extra (feromona, fijador, potencializador, etc.)'), ('OTRO', 'Otro insumo')], help_text='Solo aplica cuando el tipo de producto es Insumo.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('INSUMO', 'Insumo'), ('TERMINADO', 'Terminado (reventa)')], max_length=10),
        ),
    ]
