# Generated by Django 6.0 on 2026-07-01 23:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('origen', models.CharField(choices=[('VENTA_CONTADO', 'Venta de contado'), ('ABONO_FIADO', 'Abono a fiado'), ('PRESTAMO_RECIBIDO', 'Préstamo recibido'), ('COMPRA_CONTADO', 'Compra de contado'), ('GASTO', 'Gasto'), ('PRESTAMO_OTORGADO', 'Préstamo otorgado'), ('PAGO_PRESTAMO', 'Pago de préstamo recibido'), ('AJUSTE', 'Ajuste manual')], max_length=25)),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('saldo_resultante', models.IntegerField(editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
