# Generated by Django 6.0 on 2026-07-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('VENTA_CONTADO', 'Venta de contado'), ('ABONO_FIADO', 'Abono a fiado'), ('PRESTAMO_RECIBIDO', 'Préstamo recibido'), ('COMPRA_CONTADO', 'Compra de contado'), ('GASTO', 'Gasto'), ('PRESTAMO_OTORGADO', 'Préstamo otorgado'), ('PAGO_PRESTAMO', 'Pago de préstamo recibido'), ('COBRO_PRESTAMO', 'Cobro de préstamo otorgado'), ('AJUSTE', 'Ajuste manual')], max_length=25),
        ),
    ]
