# Generated by Django 6.0 on 2026-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito (le debemos al proveedor)')], default='CONTADO', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='pagada_en_caja',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
